### ISSUE TITLE
Mapa do jogo

### ISSUE THREAD

**Issue by artretr0** [Jackadven/exsokoban.c#1]
Primeiro issue do projeto. 

Pessoal, já hoje eu gostaria de implementar o mapa. Para já podermos imprimir ele na tela. Para isso gostaria de saber qual vai ser o tamanho da matriz que vamos usar para isso. Respondam aqui o tamanho com a qual vocês acham melhor para usar que eu já irei definir seus parâmetros.

**Comment by leandroautocontrole** [comment]
A matriz que ele passou é 7x6 (linhas x colunas).

**Comment by Jackadven** [comment]
O mapa já foi implementado e já está sendo possível imprimir na tela.
